sbom-metadata:
  - env_vars:
      - "RELATED_IMAGE_ODH_VLLM_CPU_IMAGE"
      - "RELATED_IMAGE_ODH_VLLM_CPU_FAST_1_IMAGE"
      - "RELATED_IMAGE_ODH_VLLM_CPU_FAST_2_IMAGE"
    package: "vllm"
    suffix: "_UPSTREAM_VERSION"
