
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: build-catalog
spec:
  description: |
    This pipeline is ideal for building and verifying [file-based catalogs](https://konflux-ci.dev/docs/end-to-end/building-olm/#building-the-file-based-catalog).

    _Uses `buildah` to create a container image. Its build-time tests are limited to verifying the included catalog and do not scan the image.
    This pipeline is pushed as a Tekton bundle to [quay.io](https://quay.io/repository/konflux-ci/tekton-catalog/pipeline-fbc-builder?tab=tags)_
  params:
  - description: Source Repository URL
    name: git-url
    type: string
  - default: ""
    description: Revision of the Source Repository
    name: revision
    type: string
  - description: Fully Qualified Output Image
    name: output-image
    type: string
  - default: .
    description: Path to the source code of an application's component from where
      to build image.
    name: path-context
    type: string
  - default: Dockerfile
    description: Path to the Dockerfile inside the context specified by parameter
      path-context
    name: dockerfile
    type: string
  - default: "false"
    description: Force rebuild image
    name: rebuild
    type: string
  - default: "false"
    description: Skip checks against built image
    name: skip-checks
    type: string
  - default: "false"
    description: Skip fips checks against built image
    name: skip-fips
    type: string
  - default: "true"
    description: Execute the build with network isolation
    name: hermetic
    type: string
  - default: ""
    description: Build dependencies to be prefetched
    name: prefetch-input
    type: string
  - default: ""
    description: Image tag expiration time, time values could be something like
      1h, 2d, 3w for hours, days, and weeks, respectively.
    name: image-expires-after
    type: string
  - default: "false"
    description: Build a source image.
    name: build-source-image
    type: string
  - default: "true"
    description: Add built image into an OCI image index
    name: build-image-index
    type: string
  - default: "false"
    description: Enable cache proxy configuration
    name: enable-cache-proxy
  - default: []
    description: Array of --build-arg values ("arg=value" strings) for buildah
    name: build-args
    type: array
  - default: ""
    description: Path to a file with build arguments for buildah, see https://www.mankier.com/1/buildah-build#--build-arg-file
    name: build-args-file
    type: string
  - default:
    - linux/x86_64
    description: List of platforms to build the container images on. The available
      set of values is determined by the configuration of the multi-platform-controller.
    name: build-platforms
    type: array
  - description: Additional labels to add to build image
    name: additional-labels
    type: array
    default: []
  - name: enable-slack-failure-notification
    default: "true"
    type: string
    description: Show a slack notification on failure
  - name: expected-cluster
    default: ""
    type: string
    description: The cluster that this pipeline is expected to be run from
  - name: pipeline-type
    type: string
    default: push
    description: Type of pipeline execution (push)
  results:
  - description: ""
    name: IMAGE_URL
    value: $(tasks.build-image-index.results.IMAGE_URL)
  - description: ""
    name: IMAGE_DIGEST
    value: $(tasks.build-image-index.results.IMAGE_DIGEST)
  - description: ""
    name: CHAINS-GIT_URL
    value: $(tasks.clone-repository.results.url)
  - description: ""
    name: CHAINS-GIT_COMMIT
    value: $(tasks.clone-repository.results.commit)
  tasks:
  - name: rhoai-init
    params:
    - name: expected-cluster
      value: $(params.expected-cluster)
    - name: pipeline-type
      value: $(params.pipeline-type)
    taskRef:
      resolver: git
      params:
      - name: url
        value: https://github.com/red-hat-data-services/rhoai-konflux-tasks.git
      - name: revision
        value: odh
      - name: pathInRepo
        value: konflux-tekton-tasks/rhoai-init/0.3/rhoai-init.yaml
  - name: init
    runAfter:
    - rhoai-init
    params:
    - name: image-url
      value: $(params.output-image)
    - name: rebuild
      value: $(params.rebuild)
    - name: skip-checks
      value: $(params.skip-checks)
    - name: enable-cache-proxy
      value: $(params.enable-cache-proxy)
    taskRef:
      params:
      - name: name
        value: init
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-init:0.2@sha256:b349d24cb896573695802d6913d311640b44675ec082b3ad167721946a6a0a71
      - name: kind
        value: task
      resolver: bundles
  - name: clone-repository
    params:
    - name: url
      value: $(params.git-url)
    - name: revision
      value: $(params.revision)
    - name: ociStorage
      value: $(params.output-image).git
    - name: ociArtifactExpiresAfter
      value: $(params.image-expires-after)
    runAfter:
    - init
    taskRef:
      params:
      - name: name
        value: git-clone-oci-ta
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-git-clone-oci-ta:0.1@sha256:0a89e1a6304076525e9766f63a4cd006763d21d5aca6863281fc427537a23c6f
      - name: kind
        value: task
      resolver: bundles
    when:
    - input: $(tasks.init.results.build)
      operator: in
      values:
      - "true"
    workspaces:
    - name: basic-auth
      workspace: git-auth
  - name: run-opm-command
    params:
    - name: SOURCE_ARTIFACT
      value: $(tasks.clone-repository.results.SOURCE_ARTIFACT)
    - name: ociStorage
      value: $(params.output-image).opm
    - name: ociArtifactExpiresAfter
      value: $(params.image-expires-after)
    - name: OPM_ARGS
      value: []
    - name: OPM_OUTPUT_PATH
      value: ""
    - name: IDMS_PATH
      value: ""
    runAfter:
    - clone-repository
    taskRef:
      params:
      - name: name
        value: run-opm-command-oci-ta
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-run-opm-command-oci-ta:0.1@sha256:7380c18ca13af3235c951b2df952fe1012a18708541e989fb3cb2e3caf752390
      - name: kind
        value: task
      resolver: bundles
  - name: prefetch-dependencies
    params:
    - name: input
      value: $(params.prefetch-input)
    - name: SOURCE_ARTIFACT
      value: $(tasks.run-opm-command.results.SOURCE_ARTIFACT)
    - name: ociStorage
      value: $(params.output-image).prefetch
    - name: ociArtifactExpiresAfter
      value: $(params.image-expires-after)
    runAfter:
    - run-opm-command
    taskRef:
      params:
      - name: name
        value: prefetch-dependencies-oci-ta
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-prefetch-dependencies-oci-ta:0.2@sha256:3e5e834290a1ed57fd14c0082e5a10789c8fe382ed682ef7f981475a7b316b49
      - name: kind
        value: task
      resolver: bundles
    workspaces:
    - name: git-basic-auth
      workspace: git-auth
    - name: netrc
      workspace: netrc
  - matrix:
      params:
      - name: PLATFORM
        value:
        - $(params.build-platforms)
    name: build-images
    params:
    - name: IMAGE
      value: $(params.output-image)
    - name: DOCKERFILE
      value: $(params.dockerfile)
    - name: CONTEXT
      value: $(params.path-context)
    - name: HERMETIC
      value: $(params.hermetic)
    - name: PREFETCH_INPUT
      value: $(params.prefetch-input)
    - name: IMAGE_EXPIRES_AFTER
      value: $(params.image-expires-after)
    - name: COMMIT_SHA
      value: $(tasks.clone-repository.results.commit)
    - name: BUILD_ARGS
      value:
      - $(params.build-args[*])
    - name: BUILD_ARGS_FILE
      value: $(params.build-args-file)
    - name: SOURCE_URL
      value: $(tasks.clone-repository.results.url)
    - name: HTTP_PROXY
      value: $(tasks.init.results.http-proxy)
    - name: NO_PROXY
      value: $(tasks.init.results.no-proxy)
    - name: SOURCE_ARTIFACT
      value: $(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)
    - name: CACHI2_ARTIFACT
      value: $(tasks.prefetch-dependencies.results.CACHI2_ARTIFACT)
    - name: IMAGE_APPEND_PLATFORM
      value: "true"
    - name: LABELS
      value:
      - $(params.additional-labels[*])
      - git.url=$(params.git-url)
      - git.commit=$(params.revision)
      - build-url=$(tasks.rhoai-init.results.build-url)
    runAfter:
    - clone-repository
    taskRef:
      params:
      - name: name
        value: buildah-remote-oci-ta
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-buildah-remote-oci-ta:0.7@sha256:ef1c062b10c9fb17951350de76bce6bb54a4ea75fca4f37ea136d626c444bf78
      - name: kind
        value: task
      resolver: bundles
    when:
    - input: $(tasks.init.results.build)
      operator: in
      values:
      - "true"
  - name: build-image-index
    params:
    - name: IMAGE
      value: $(params.output-image)
    - name: COMMIT_SHA
      value: $(tasks.clone-repository.results.commit)
    - name: IMAGE_EXPIRES_AFTER
      value: $(params.image-expires-after)
    - name: ALWAYS_BUILD_INDEX
      value: $(params.build-image-index)
    - name: IMAGES
      value:
      - $(tasks.build-images.results.IMAGE_REF[*])
    runAfter:
    - build-images
    taskRef:
      params:
      - name: name
        value: build-image-index
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-build-image-index:0.2@sha256:39561ac43e325159497c10c0284cf61dfddf39e39100ca5e3df6b73c5d96db8b
      - name: kind
        value: task
      resolver: bundles
    when:
    - input: $(tasks.init.results.build)
      operator: in
      values:
      - "true"
  - name: deprecated-base-image-check
    params:
    - name: IMAGE_URL
      value: $(tasks.build-image-index.results.IMAGE_URL)
    - name: IMAGE_DIGEST
      value: $(tasks.build-image-index.results.IMAGE_DIGEST)
    runAfter:
    - build-image-index
    taskRef:
      params:
      - name: name
        value: deprecated-image-check
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-deprecated-image-check:0.5@sha256:462baed733dfc38aca5395499e92f19b6f13a74c2e88fe5d86c3cffa2f899b57
      - name: kind
        value: task
      resolver: bundles
    when:
    - input: $(params.skip-checks)
      operator: in
      values:
      - "false"
  - name: apply-tags
    params:
    - name: IMAGE_URL
      value: $(tasks.build-image-index.results.IMAGE_URL)
    - name: IMAGE_DIGEST
      value: $(tasks.build-image-index.results.IMAGE_DIGEST)
    runAfter:
    - build-image-index
    taskRef:
      params:
      - name: name
        value: apply-tags
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-apply-tags:0.2@sha256:e4017ec351a0891ef95989f35bd20b8c3f091fa1a3da364c4d4e975e99f3063c
      - name: kind
        value: task
      resolver: bundles
  - name: validate-fbc
    params:
    - name: IMAGE_URL
      value: $(tasks.build-image-index.results.IMAGE_URL)
    - name: IMAGE_DIGEST
      value: $(tasks.build-image-index.results.IMAGE_DIGEST)
    runAfter:
    - build-image-index
    taskRef:
      params:
      - name: name
        value: validate-fbc
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-validate-fbc:0.1@sha256:2a99dbde96bca33d414a96acc5ab39886b53d91c37ef8bd872ea47bfbe1b319f
      - name: kind
        value: task
      resolver: bundles
    when:
    - input: $(params.skip-checks)
      operator: in
      values:
      - "false"
  - name: fbc-target-index-pruning-check
    params:
    - name: IMAGE_URL
      value: $(tasks.build-image-index.results.IMAGE_URL)
    - name: IMAGE_DIGEST
      value: $(tasks.build-image-index.results.IMAGE_DIGEST)
    - name: TARGET_INDEX
      value: registry.redhat.io/redhat/redhat-operator-index
    - name: RENDERED_CATALOG_DIGEST
      value: $(tasks.validate-fbc.results.RENDERED_CATALOG_DIGEST)
    runAfter:
    - validate-fbc
    taskRef:
      params:
      - name: name
        value: fbc-target-index-pruning-check
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-fbc-target-index-pruning-check:0.1@sha256:216200a63475889d9ca17ef331322335f77ff17655add588b8b04c240297dc89
      - name: kind
        value: task
      resolver: bundles
    when:
    - input: $(params.skip-checks)
      operator: in
      values:
      - "false"
  - name: fbc-fips-check-oci-ta
    params:
    - name: image-digest
      value: $(tasks.build-image-index.results.IMAGE_DIGEST)
    - name: image-url
      value: $(tasks.build-image-index.results.IMAGE_URL)
    - name: SOURCE_ARTIFACT
      value: $(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)
    runAfter:
    - build-image-index
    taskRef:
      params:
      - name: name
        value: fbc-fips-check-oci-ta
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-fbc-fips-check-oci-ta:0.1@sha256:8f62bc6937382c5acc87e0dafff70c11457fb91e27f01644b30cb68dc8ef3d28
      - name: kind
        value: task
      resolver: bundles
    when:
    - input: $(params.skip-checks)
      operator: notin
      values:
      - "true"
    - input: $(params.skip-fips)
      operator: notin
      values:
      - "true"
  - name: prepare-slack-message
    params:
    taskSpec:
      results:
      - description: Notification text to be posted to slack
        name: slack-message-success-text
      steps:
      - image: quay.io/rhoai/rhoai-task-toolset:odh-nightly-runner
        name: prepare-slack-message
        env:
        - name: pipelinerun_name
          value: "$(context.pipelineRun.name)"
        - name: IMAGE_REF
          value: $(tasks.build-image-index.results.IMAGE_REF)
        - name: MESSAGE_TEMPLATE
          valueFrom:
            configMapKeyRef:
              name: slack-config
              key: catalog-ci-message-template
        - name: target_branch
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['build.appstudio.redhat.com/target_branch']
        - name: BUILD_URL
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['pipelinesascode.tekton.dev/log-url']
        - name: COMMIT_URL
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['pipelinesascode.tekton.dev/sha-url']
        - name: COMMIT
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['pipelinesascode.tekton.dev/sha']
        script: |
          echo "pipelinerun-name = $pipelinerun_name"

          application_name=${target_branch/rhoai-/}
          application_name=rhoai-v${application_name/./-}
          echo "application-name = $application_name"
          echo "image url = $image_url"
          echo "image digest = $image_digest"

          component_name=${pipelinerun_name/-on-*/}
          echo "component-name = $component_name"

          export build_time="$(date +%Y-%m-%dT%H:%M:%S)"
          export COMMIT_SHORT=$(echo "$COMMIT" | head -c 7)
          SUBST_VARS='$build_time $IMAGE_REF $COMMIT_URL $COMMIT_SHORT $BUILD_URL $pipelinerun_name'
          echo "$MESSAGE_TEMPLATE" | envsubst "$SUBST_VARS" | tee "$(results.slack-message-success-text.path)"
    runAfter:
    - build-image-index
  - name: pipeline-success-indicator
    runAfter:
    - deprecated-base-image-check
    - apply-tags
    taskSpec:
      steps:
      - name: noop
        image: quay.io/rhoai-konflux/alpine:latest
        script: |
          echo "Success"
  finally:
  - name: send-slack-notification
    params:
    - name: message
      value: "$(tasks.rhoai-init.results.slack-message-failure-text)"
    - name: secret-name
      value: ci-slack-secret
    - name: key-name
      value: secret
    taskRef:
      params:
      - name: name
        value: slack-webhook-notification
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-slack-webhook-notification:0.1@sha256:69945a30c11387a766e3d0ae33991b68e865a290c09da1fea44f193d358926ba
      - name: kind
        value: task
      resolver: bundles
    when:
    - input: $(tasks.pipeline-success-indicator.status)
      operator: notin
      values:
      - "Succeeded"
    - input: $(tasks.rhoai-init.results.skip-slack-message)
      operator: in
      values:
      - "false"
    - input: $(params.enable-slack-failure-notification)
      operator: in
      values:
      - "true"
    - input: $(params.pipeline-type)
      operator: in
      values:
        - "push"
  - name: share-fbc-details
    workspaces:
    - name: basic-auth
      workspace: git-auth
    taskSpec:
      steps:
      - image: quay.io/rhoai/rhoai-task-toolset:odh-nightly-runner
        env:
        - name: HOME
          value: /workspace
        - name: SLACK_TOKEN
          valueFrom:
            secretKeyRef:
              name: rhoai-devops-bot-slack-token
              key: SLACK_TOKEN
        - name: MESSAGE
          value: $(tasks.prepare-slack-message.results.slack-message-success-text)
        - name: IMAGE_REF
          value: $(tasks.build-image-index.results.IMAGE_REF)
        - name: CHANNEL
          valueFrom:
            configMapKeyRef:
              name: slack-config
              key: odh-notification-channel
        workingDir: /workspace
        script: |
          #!/bin/bash
          set -e
          export GIT_SSH_COMMAND="ssh -F $HOME/.ssh/config -o UserKnownHostsFile=$HOME/.ssh/known_hosts"
          mkdir slack && cd slack
          git init .
          git remote add origin git@github.com:red-hat-data-services/rhods-devops-infra.git
          git fetch origin main
          git show origin/main:tools/send-slack-message/send-slack-message.sh > ./send-slack-message.sh
          git show origin/main:tools/tracer/tracer.sh > ./tracer.sh
          chmod +x ./send-slack-message.sh
          chmod +x ./tracer.sh

          ./tracer.sh --odh -i "$IMAGE_REF" --show-commits | tee tracer-output.txt
          ./send-slack-message.sh -c "$CHANNEL" -m "$MESSAGE" -f tracer-output.txt -v
    when:
    - input: $(tasks.status)
      operator: in
      values:
      - "Completed"
      - "Succeeded"
    - input: $(params.pipeline-type)
      operator: in
      values:
        - "push"
  workspaces:
  - name: git-auth
    optional: true
  - name: netrc
    optional: true
