---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: odh-pr-test
spec:
  description: |
    An integration test which provisions an ephemeral Hypershift cluster, deploys opendatahub-operator 
    from a Konflux snapshot and runs the e2e tests against it.
  params:
    - description: Snapshot of the application
      name: SNAPSHOT
      type: string
  #test
  tasks:
    - name: parse-metadata
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/konflux-ci/integration-examples
          - name: revision
            value: main
          - name: pathInRepo
            value: tasks/test_metadata.yaml
          - name: token
            value: github-token-secret
          - name: tokenKey
            value: token
      params:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
    - name: check-prerequisites
      description: check prerequisites if the ITS needs to execute
      runAfter:
        - parse-metadata
      taskSpec:
        results:
        - name: event-type
          description: "stores info about event type"
        steps:
        - image: quay.io/konflux-ci/konflux-test:stable
          env:
            - name: EVENT_TYPE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['pac.test.appstudio.openshift.io/event-type']
          script: |
            #!/bin/bash
            set -e
            echo "EVENT_TYPE=${EVENT_TYPE}"
            echo -n "${EVENT_TYPE}" > $(results.event-type.path)
    - name: find-component-image
      description: Placeholder task that prints the Snapshot and outputs standard TEST_OUTPUT
      runAfter:
        - check-prerequisites
      params:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
      taskSpec:
        params:
        - name: SNAPSHOT
        steps:
        - image: quay.io/konflux-ci/konflux-test:stable
          workingDir: /workspace
          env:
            - name: SNAPSHOT
              value: $(params.SNAPSHOT)
            - name: COMPONENT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['appstudio.openshift.io/component']
          script: |
            #!/bin/sh
    
            # Extract the component container image from the SNAPSHOT JSON data
            COMPONENT_CONTAINER_IMAGE=$(jq -r --arg component_name "${COMPONENT_NAME}" '.components[] | select(.name == $component_name) | .containerImage' <<< "${SNAPSHOT}")
    
            # Log the extracted variable
            echo "  COMPONENT_CONTAINER_IMAGE: ${COMPONENT_CONTAINER_IMAGE}"
      when:
        - input: "$(tasks.check-prerequisites.results.event-type)"
          operator: in
          values: ["pull_request", "retest-all-comment"]
    - name: provision-eaas-space
      runAfter:
        - check-prerequisites
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/konflux-ci/build-definitions.git
          - name: revision
            value: main
          - name: pathInRepo
            value: task/eaas-provision-space/0.1/eaas-provision-space.yaml
          - name: token
            value: github-token-secret
          - name: tokenKey
            value: token
      params:
        - name: ownerName
          value: $(context.pipelineRun.name)
        - name: ownerUid
          value: $(context.pipelineRun.uid)
      when:
        - input: "$(tasks.check-prerequisites.results.event-type)"
          operator: in
          values: ["pull_request", "retest-all-comment"]
    - name: provision-cluster
      runAfter:
        - provision-eaas-space
      taskSpec:
        results:
          - name: clusterName
            value: "$(steps.create-cluster.results.clusterName)"
        steps:
          - name: get-supported-versions
            ref:
              resolver: git
              params:
                - name: url
                  value: https://github.com/konflux-ci/build-definitions.git
                - name: revision
                  value: main
                - name: pathInRepo
                  value: stepactions/eaas-get-supported-ephemeral-cluster-versions/0.1/eaas-get-supported-ephemeral-cluster-versions.yaml
                - name: token
                  value: github-token-secret
                - name: tokenKey
                  value: token
            params:
              - name: eaasSpaceSecretRef
                value: $(tasks.provision-eaas-space.results.secretRef)
          - name: pick-version
            ref:
              resolver: git
              params:
                - name: url
                  value: https://github.com/konflux-ci/build-definitions.git
                - name: revision
                  value: main
                - name: pathInRepo
                  value: stepactions/eaas-get-latest-openshift-version-by-prefix/0.1/eaas-get-latest-openshift-version-by-prefix.yaml
                - name: token
                  value: github-token-secret
                - name: tokenKey
                  value: token
            params:
              - name: prefix
                value: "$(steps.get-supported-versions.results.versions[0])."
          - name: create-cluster
            ref:
              resolver: git
              params:
                - name: url
                  value: https://github.com/konflux-ci/build-definitions.git
                - name: revision
                  value: main
                - name: pathInRepo
                  value: stepactions/eaas-create-ephemeral-cluster-hypershift-aws/0.1/eaas-create-ephemeral-cluster-hypershift-aws.yaml
                - name: token
                  value: github-token-secret
                - name: tokenKey
                  value: token
            params:
              - name: eaasSpaceSecretRef
                value: $(tasks.provision-eaas-space.results.secretRef)
              - name: version
                value: "$(steps.pick-version.results.version)"
              - name: instanceType
                value: m5.2xlarge
      when:
        - input: "$(tasks.check-prerequisites.results.event-type)"
          operator: in
          values: ["pull_request"]
    - name: deploy-and-test
      runAfter:
        - provision-cluster
      params:
      - name: git-url
        value: "$(tasks.parse-metadata.results.source-git-url)"
      - name: git-rev
        value: "$(tasks.parse-metadata.results.target-git-branch)"
      - name: component-image
        value: "$(tasks.parse-metadata.results.component-container-image)"
      taskSpec:
        volumes:
          - name: credentials
            emptyDir: {}
        steps:
          - name: get-kubeconfig
            ref:
              resolver: git
              params:
                - name: url
                  value: https://github.com/konflux-ci/build-definitions.git
                - name: revision
                  value: main
                - name: pathInRepo
                  value: stepactions/eaas-get-ephemeral-cluster-credentials/0.1/eaas-get-ephemeral-cluster-credentials.yaml
                - name: token
                  value: github-token-secret
                - name: tokenKey
                  value: token
            params:
              - name: eaasSpaceSecretRef
                value: $(tasks.provision-eaas-space.results.secretRef)
              - name: clusterName
                value: "$(tasks.provision-cluster.results.clusterName)"
              - name: credentials
                value: credentials
          - name: deploy-and-e2e
            image: quay.io/rhoai/rhoai-task-toolset:its
            env:
              - name: KUBECONFIG
                value: "/credentials/$(steps.get-kubeconfig.results.kubeconfig)"
            workingDir: /workspace/source
            volumeMounts:
              - name: credentials
                mountPath: /credentials
            script: |
              oc get pods
              oc whoami