---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: odh-pr-test
spec:
  description: |
    An integration test which provisions an ephemeral Hypershift cluster, deploys opendatahub-operator 
    from a Konflux snapshot and runs the e2e tests against it.
  params:
    - description: Snapshot of the application
      name: SNAPSHOT
      type: string
  tasks:
    - name: parse-metadata
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/konflux-ci/integration-examples
          - name: revision
            value: main
          - name: pathInRepo
            value: tasks/test_metadata.yaml
          - name: token
            value: github-token-secret
          - name: tokenKey
            value: token
      params:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)